image: node:8

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
stages:
  - staging
  - production

deploy_staging:
  stage: staging
  script:
    - ssh root@ansible.ebaba.com bash --login "./run-ansible-devfe.sh"
  only:
  - develop

deploy_production:
  type: deploy
  stage: production
  environment: production
  script:
    - ssh root@ansible.ebaba.com bash --login "./run-ansible-prodfe.sh"
  only:
  - master
  when: manual
