const cartConstants = {
  ADD_TOCART: 'ADD_TOCART',
  COUNT_CART: 'COUNT_CART',
  DELETE_ITEM: 'DELETE_ITEM',
  ITEM_ADDED: 'ITEM_ADDED',
  REMOVE_ITEM_ADDED: 'REMOVE_ITEM_ADDED',
  LIST_CART: 'LIST_CART',
  END_TRANSACTION: 'END_TRANSACTION',
};

export default cartConstants;
