const homeConstants = {
  GET_PRODUCT: 'GET_PRODUCT',
  GET_DETAIL: 'GET_DETAIL',
  GET_SORTED_PRODUCT: 'GET_SORTED_PRODUCT',
  GET_PRODUCT_BY_CATEGORY: 'GET_PRODUCT_BY_CATEGORY',
  FETCHING: 'FETCHING',
  FETCHING_PAGINATION: 'FETCHING_PAGINATION',
  RESET_PRODUCTS: 'RESET_PRODUCTS',
  SEARCH_PRODUCTS: 'SEARCH_PRODUCTS',
  GET_HEADLINES: 'GET_HEADLINES'
};

export default homeConstants;
