const shippingConstants = {
  ADD_SHIPPING_DETAIL: 'ADD_SHIPPING_DETAIL',
  ADD_SHIPPING_PAYMENT: 'ADD_SHIPPING_PAYMENT',
  CHECKOUT: 'CHECKOUT',
  GET_PROVINCE: 'GET_PROVINCE',
  GET_CITY: 'GET_CITY',
  GET_DISTRICT: 'GET_DISTRICT',
  END_TRANSACTION: 'END_TRANSACTION',

  REQUEST_SHIPPING_STATUS: 'GET_SHIPPING_STATUS',
  SUCCESS_SHIPPING_STATUS: 'SUCCESS_GET_SHIPPING_STATUS',
  FAILED_SHIPPING_STATUS: 'FAILED_GET_SHIPPING_STATUS'
};

export default shippingConstants;
