const vendorConstants = {
    GET_PRODUCT_BY_VENDOR: 'GET_PRODUCT_BY_VENDOR',
    GET_DETAIL_VENDOR: 'GET_DETAIL_VENDOR',
    RESET_VENDOR_PRODUCTS: 'RESET_VENDOR_PRODUCTS',
    FETCH_LIST_PRODUCT_BY_VENDOR: 'FETCH_LIST_PRODUCT_BY_CATEGORY'
  };
  
  export default vendorConstants;
  